# Generated by Django 4.2.5 on 2023-11-06 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_groups_usuario_is_staff_usuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Continente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('id_do_continente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.continente')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('id_da_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('id_do_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Registrar_Fornecedor_mercadoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=50)),
                ('telefone', models.CharField(max_length=150)),
                ('endereco', models.CharField(max_length=150)),
                ('continente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.continente')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.municipio')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pais')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Registrar_Localizacao_mercadoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=50)),
                ('telefone', models.CharField(max_length=150)),
                ('endereco', models.CharField(max_length=150)),
                ('continente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.continente')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.municipio')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pais')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.provincia')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nif',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.CreateModel(
            name='Submeter_Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
                ('total_pago', models.FloatField()),
                ('data_da_compra', models.DateField()),
                ('peso', models.FloatField()),
                ('dimensao', models.CharField(max_length=150)),
                ('marca', models.CharField(max_length=150)),
                ('modelo', models.CharField(max_length=150)),
                ('ficheiro_da_fatura', models.ImageField(upload_to='')),
                ('destino_da_mercadoria_continente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.continente')),
                ('destino_da_mercadoria_municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.municipio')),
                ('destino_da_mercadoria_pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pais')),
                ('destino_da_mercadoria_provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.provincia')),
                ('id_da_categoria_produto', models.ManyToManyField(to='core.categoria')),
                ('id_da_localizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localizacao', to='core.registrar_localizacao_mercadoria')),
                ('id_do_fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fornecedor', to='core.registrar_fornecedor_mercadoria')),
                ('id_do_produto', models.ManyToManyField(to='core.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Registrar_Certificado_Camara_Comercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=1000)),
                ('certificado', models.ImageField(upload_to='')),
                ('id_da_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.submeter_factura')),
            ],
        ),
        migrations.AddField(
            model_name='municipio',
            name='id_da_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.provincia'),
        ),
    ]
