# Generated by Django 4.2.5 on 2023-11-15 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tipousuario_alter_produto_id_da_categoria_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submeter_factura',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submeter_factura',
            name='destino_da_mercadoria_continente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.continente'),
        ),
        migrations.AlterField(
            model_name='submeter_factura',
            name='destino_da_mercadoria_municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.municipio'),
        ),
        migrations.AlterField(
            model_name='submeter_factura',
            name='destino_da_mercadoria_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pais'),
        ),
        migrations.AlterField(
            model_name='submeter_factura',
            name='destino_da_mercadoria_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.provincia'),
        ),
        migrations.AlterField(
            model_name='submeter_factura',
            name='id_da_localizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizacao', to='core.registrar_localizacao_mercadoria'),
        ),
        migrations.AlterField(
            model_name='submeter_factura',
            name='id_do_fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedor', to='core.registrar_fornecedor_mercadoria'),
        ),
    ]
