# Generated by Django 4.2.5 on 2023-11-15 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_submeter_factura_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='tipo_de_entidade',
            new_name='tipo_de_usuario',
        ),
    ]
